[package]
name = "remnawave-healthcheck-ssh"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Node-side checks over SSH for remnawave-healthcheck"

[dependencies]
remnawave-healthcheck-core = { path = "../core" }
chrono.workspace = true
tokio.workspace = true
